language: python
python:
  - "2.7"
before_install:
  - "ci/travis.sh"   
install:
  - "pip install -r requirements.txt"
  - "sudo cp ci/distributed-flock.json /etc/distributed-flock.json"
  - "sudo apt-get install zookeeper zookeeperd"
  - "sudo /usr/share/zookeeper/bin/zkServer.sh start"
script: "test \"$(zk-flock | head -n1)\" == \"Invalid number of arguments\" && python setup.py nosetests"
after_success: coveralls
